### ISSUE TITLE
Thorwing error URL is not defined

### ISSUE THREAD

**Issue by shafikulz** [CodementorIO/nextjs-redux-starter#47]
/nextjs-redux-starter/node_modules/next/dist/next-server/lib/router/utils/parse-relative-url.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";exports.__esModule=true;exports.parseRelativeUrl=parseRelativeUrl;var _utils=require("../../utils");const DUMMY_BASE=new URL(typeof window==='undefined'?'http://n':(0,_utils.getLocationOrigin)());/**
                                                                                                                                                                                                ^

ReferenceError: URL is not defined
    at Object.<anonymous> /nextjs-redux-starter/node_modules/next/dist/next-server/lib/router/utils/parse-relative-url.js:1:193)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/nextjs-redux-starter/node_modules/next/dist/next-server/lib/router/utils/prepare-destination.js:1:199)
    at Module._compile (module.js:653:30)

**Comment by santoshvijapure** [comment]
@shafikulz was you able to resolve this issue? I'm having a similar issue.
